name: Bug report
description: File a bug report if MultiQC is breaking / not behaving in the way you expect
body:
  - type: textarea
    id: description
    attributes:
      label: Description of bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: MultiQC Error log
      description: Please paste your full MultiQC log.
      render: console

  - type: textarea
    id: error-file
    attributes:
      label: File that triggers the error
      description: Please drag and drop (and upload to the GitHub issue) an input file that can be used to replicate the error. Please don't copy and paste log contents, as important whitespace can change. If the file type is not allowed, please compress into a `.zip` file and try again.

  - type: input
    id: command
    attributes:
      label: Command used to run MultiQC
      placeholder: eg. multiqc .

  - type: input
    id: version
    attributes:
      label: MultiQC Version
      placeholder: eg. MultiQC v1.10

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: eg. macOS Sierra 10.12.5

  - type: input
    id: python
    attributes:
      label: Python Version
      placeholder: eg. Python 3.8.4

  - type: input
    id: installation
    attributes:
      label: Method of MultiQC installation
      placeholder: eg. pip, conda, manual
