contact_links:
  - name: MultiQC Documentation
    url: https://docs.seqera.io/multiqc/
    about: Make sure you've checked the documentation first.
  - name: MultiQC Community forums
    url: https://community.seqera.io
    about: You can ask quick questions on the community forum.
