name: Module request
description: Request support for a new bioinformatics tool in MultiQC
labels: ["module: new"]
body:
  - type: input
    id: name
    attributes:
      label: Name of the tool
      placeholder: eg. My Tool
    validations:
      required: true

  - type: input
    id: homepage
    attributes:
      label: Tool homepage
      placeholder: eg. http://www.github/me/mytool
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: Tool description
      description: A short single-sentence description that will be used in the modules listing on the MultiQC homepage.
      placeholder: eg. My Tool is a really excellent tool that does what no other tool can do
    validations:
      required: true

  - type: textarea
    id: example-files
    attributes:
      label: Tool output
      description: |
        Please drag and drop (and upload to the GitHub issue) some example files that can be used to write the module.
        ***Please do not copy and paste log contents***, as important whitespace can change.
        If the file type is not allowed, please compress into a `.zip` file.
        If the file is many MBs then it's ok to truncate it, though please leave a few lines of data in so that it's clear what the format is.
      placeholder: "[ Drag and drop some example files here to upload ]"
    validations:
      required: true

  - type: input
    id: filename-pattern
    attributes:
      label: Log filename pattern
      description: |
        Specify the filename pattern only if standardised by the tool and **NOT** specified by user. It must be consistent for all runs of tool by any user.
        Leave blank if the tool does not have a standard file naming pattern (eg. printing to standard out, or taking free text filename as a command line option).
      placeholder: eg. *_mytool.txt

  - type: textarea
    id: plots
    attributes:
      label: Data suitable for MultiQC plot(s)
      description: |
        What data in the tool output is most important - what would you like to see in a plot or dedicated table?
        Remember that MultiQC should just highlight the important bits - enough to spot outlier samples for further examination.

  - type: textarea
    id: general-stats
    attributes:
      label: Most interesting data for the General Stats table
      description: Is there 1-3 values that would be helpful to have in the _General Statistics_ table, alongside results from other tools?

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      description: >-
        Please ensure your module request fulfills all of the following requirements.
      options:
        - label: >-
            I have included example data (zipped, not pasted) that can be used to write the module.
          required: true
