"""
Generate docs/modules/<module.md> files for each module in MultiQC from the MultiqcModule class docstrings.

Usage:

    python scripts/make_module_docs.py
    python scripts/make_module_docs.py samtools
"""

import os
from typing import Dict

import yaml

import argparse
from pathlib import Path
from textwrap import dedent

from multiqc import config, report, BaseMultiqcModule

test_data_dir = Path("test-data")
if not test_data_dir.exists():
    raise RuntimeError("Please clone https://github.com/MultiQC/test-data into test-data/")

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("module", help="Generate for a specific module", nargs="?")
args = parser.parse_args()

sp_by_mod: Dict[str, Dict] = dict()
with (Path(config.MODULE_DIR) / "search_patterns.yaml").open() as f:
    for k, v in yaml.safe_load(f).items():
        mod_id = k.split("/")[0]
        sp_by_mod.setdefault(mod_id, {})[k] = v


os.makedirs("docs/markdown/modules", exist_ok=True)

# Table in the index page
table = "| Tool | Description |"
table += "\n| --- | --- |"

for mod_id, entry_point in config.avail_modules.items():
    if mod_id == "custom_content":
        continue

    mod_data_dir = test_data_dir / "data" / "modules" / mod_id
    assert mod_data_dir.exists() and mod_data_dir.is_dir(), mod_data_dir
    report.analysis_files = [mod_data_dir]
    report.search_files([mod_id])

    module_cls = entry_point.load()
    docstring = module_cls.__doc__ or ""

    module: BaseMultiqcModule = module_cls()
    table += f"\n| [{module.name}](modules/{mod_id}.md) | {module.info} |"

    if args.module and args.module != mod_id:
        continue

    if module.extra:
        extra = "\n".join(line.strip() for line in module.extra.split("\n") if line.strip())
        extra += "\n\n"
    else:
        extra = ""

    text = f"""\
---
title: {module.name}
description: >
  {module.info}
---

<!--
~~~~~ DO NOT EDIT ~~~~~
This file is autogenerated from the MultiQC module python docstring.
Do not edit the markdown, it will be overwritten.

File path for the source of this content: multiqc/modules/{mod_id}/{mod_id}.py
~~~~~~~~~~~~~~~~~~~~~~~
-->

:::note
{module.info}

{", ".join([f"[{href}]({href})" for href in module.href])}
:::

{extra}{dedent(docstring)}

### File search patterns

```yaml
{yaml.dump(sp_by_mod[mod_id]).strip()}
```
""".strip()

    # Remove double empty lines
    while "\n\n\n" in text:
        text = text.replace("\n\n\n", "\n\n")

    output_path = Path("docs") / "markdown" / "modules" / f"{mod_id}.md"
    with output_path.open("w") as fh:
        fh.write(text)

    print(f"Generated {output_path}")


with (Path("docs") / "markdown" / "modules.mdx").open("w") as fh:
    fh.write(f"""\
---
title: MultiQC Modules
description: Tools supported by MultiQC
---
             
MultiQC currently has modules to support {len(config.avail_modules)} bioinformatics tools, listed below.

Click the tool name to go to the MultiQC documentation for that tool.

:::tip[Missing something?]
If you would like another tool to to be supported, please [open an issue](https://github.com/MultiQC/MultiQC/issues/new?labels=module%3A+new&template=module-request.yml).
:::

{table}

""")
