name: Update CHANGELOG.md

on:
  pull_request_review:
    branches:
      - master
    types:
      - submitted
  # For manually triggering this workflow
  workflow_dispatch:
    inputs:
      number:
        description: PR number
        required: true
env:
  PR_TITLE: ${{ github.event.pull_request.title }} # this is returning empty
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  update_changelog:
    if: github.repository_owner == 'ewels' && github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Update CHANGELOG.md from the PR title
        run: python ${GITHUB_WORKSPACE}/.github/workflows/changelog.py

      - name: Check if CHANGELOG.md actually changed
        run: |
          git diff --exit-code CHANGELOG.md || echo "changed=YES" >> $GITHUB_ENV
          echo "file changed: ${{ env.changed }}"

      - name: Commit and push if changed
        if: env.changed == 'YES'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md"
          # Fetch the latest changes from the PR's branch
          git fetch origin ${{ github.event.pull_request.head.ref }}  
          # Rebase your local changes on top of the latest changes in the PR's branch
          git rebase FETCH_HEAD  
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
