name: Update CHANGELOG.md

on:
  pull_request_target:
    branches:
      - master
    types:
      - closed
  # For manually triggering this workflow
  workflow_dispatch:
    inputs:
      number:
        description: PR number
        required: true
env:
  PR_TITLE: ${{ github.event.pull_request.title }} # this is returning empty
  PR_NUMBER: ${{ github.event.number }}

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ewels'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Update CHANGELOG.md from the PR title
        run: python ${GITHUB_WORKSPACE}/.github/workflows/changelog.py

      - name: Check if CHANGELOG.md actually changed
        id: checkfile
        run: |
          git diff --exit-code CHANGELOG.md || echo "changed=YES" >> $GITHUB_ENV
          echo "file changed: ${{ env.changed }}"

      - name: Commit and push if changed
        if: env.changed == 'YES'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md for PR #${{ github.event.pull_request.number }}"
          git push
