name: Claude Code Review Trigger

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  trigger:
    runs-on: ubuntu-latest
    # Only run on PR comments (issue_comment fires for both issues and PRs)
    # or when PR is opened
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' &&
       github.event.issue.pull_request &&
       contains(github.event.comment.body, '/review'))

    steps:
      - name: Trigger review workflow
        run: echo "This workflow triggers the claude-code-review workflow via workflow_run"
