name: Update CSP.txt
on:
  pull_request_target:
    types: [opened]

jobs:
  update_csp:
    if: github.repository_owner == 'MultiQC' && github.event_name == 'pull_request_target'

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MQC_BOT_GITHUB_TOKEN }}

      # Action runs on the issue comment, so we don't get the PR by default.
      # Use the GitHub CLI to check out the PR:
      - name: Checkout Pull Request
        env:
          GH_TOKEN: ${{ secrets.MQC_BOT_GITHUB_TOKEN }}
        run: |
          if [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
            PR_NUMBER="${{ github.event.pull_request.number }}"
          fi
          gh pr checkout $PR_NUMBER

      - uses: actions/setup-python@v5

      - name: Update CSP whitelist
        if: matrix.python-version == env.latest_python
        run: |
          python ${GITHUB_WORKSPACE}/.github/workflows/update_csp.py \
          --whitelist ${GITHUB_WORKSPACE}/CSP.txt

      - name: Check if CSP.txt changed
        run: |
          git diff --exit-code ${GITHUB_WORKSPACE}/CSP.txt || echo "changed=YES" >> $GITHUB_ENV
          echo "File changed: ${{ env.changed }}"

      - name: Commit and push CSP.txt changes
        env:
          GH_TOKEN: ${{ secrets.MQC_BOT_GITHUB_TOKEN }}
        if: env.changed == 'YES'
        run: |
          git config user.name 'MultiQC Bot'
          git config user.email 'multiqc-bot@seqera.io'
          git config push.default upstream
          git add ${GITHUB_WORKSPACE}/CSP.txt
          git status
          git commit -m "[automated] Update CSP.txt"
          git push
