name: "Docker image"

on:
  pull_request:
    paths:
      # Step takes 30 min, too long for PR commits, so leaving it only to significant changes
      # - "pyproject.toml"
      - "Dockerfile"
  push:
    # Build multiqc:dev on every push to main
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "*.md"
  release:
    # Build release
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    if: github.repository == 'MultiQC/MultiQC'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        v:
          - lab: ""
            build_args: ""
          - lab: "pdf-"
            build_args: "INSTALL_PANDOC=true"
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      # https://github.com/docker/setup-qemu-action
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      # https://github.com/docker/setup-buildx-action
      - name: "Set up Docker Buildx"
        id: buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: "Log in to Docker Hub"
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build dev"
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        if: github.event_name != 'release'
        with:
          # All available with python:3.X-slim are:
          # platforms: linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          # But 32-bit binaries likely require compilation from source so stick with linux/amd64 and linux/arm64 for now
          platforms: linux/amd64,linux/arm64
          build-args: ${{ matrix.v.build_args }}
          # Only push if it's commit to main, or workflow_dispatch
          push: ${{github.event_name != 'pull_request'}}
          tags: |
            multiqc/multiqc:${{matrix.v.lab}}dev
            ghcr.io/multiqc/multiqc:${{matrix.v.lab}}dev

      - name: "Build release"
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        if: github.event_name == 'release'
        with:
          # All available with python:3.X-slim are:
          # platforms: linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          # But 32-bit binaries likely require compilation from source so stick with linux/amd64 and linux/arm64 for now
          platforms: linux/amd64,linux/arm64
          build-args: ${{ matrix.v.build_args }}
          push: true
          tags: |
            multiqc/multiqc:${{ matrix.v.lab }}${{ github.event.release.tag_name }}
            multiqc/multiqc:${{ matrix.v.lab }}latest
            ghcr.io/multiqc/multiqc:${{ matrix.v.lab }}${{ github.event.release.tag_name }}
            ghcr.io/multiqc/multiqc:${{ matrix.v.lab }}latest
