name: "MultiQC lint"
on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: j178/prek-action@4e14d07f9231acabce116ccfca13b13dd9755ece # v3.0.0

  code_checks:
    name: "code_checks.py"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14" # NB: 3.14.1 has upstream bug
          cache: "pip"

      - run: pip install rich

      - name: "Run manual code style checks"
        run: python ${GITHUB_WORKSPACE}/.github/workflows/code_checks.py
