name: "Mypy"
on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "*.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"

permissions:
  contents: read

jobs:
  mypy:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ["3.9", "3.14"] # NB: 3.14.1 has upstream bug

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - run: pip install '.[dev]'
      - run: mypy multiqc
      - run: mypy tests
