name: Docs screenshots
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rich_codex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out MultiQC code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install MultiQC
        run: pip install .

      - name: Download test data
        run: |
          wget https://github.com/MultiQC/test-data/archive/refs/heads/main.zip
          unzip main.zip
          mv test-data-main/ test-data/

      - name: Generate terminal images with rich-codex
        uses: ewels/rich-codex@80de9de011c994f32274bb4cffee140567621d8e # v1.2.11
        with:
          clean_img_paths: docs/images/screenshots/*.svg
          commit_changes: "true"
          skip_git_checks: "true"
