name: Push changelog to Seqera Docs

on:
  release:
    types: [published]
  workflow_dispatch:
  # Temporarilty trigger workflow on commit for testing:
  push:
    branches:
      - create-changelog-pr-to-docs

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git user for the bot
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Clone seqeralabs/docs
        run: |
          git clone https://github.com/seqeralabs/docs.git seqeralabs-docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Convert changelog
        id: convert
        run: python scripts/changelog_to_docs.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.SEQERALABS_DOCS }}
          path: seqeralabs-docs
          commit-message: "Changelog: MultiQC ${{ steps.convert.outputs.version }}"
          title: "Changelog: MultiQC ${{ steps.convert.outputs.version }}"
          body: |
            This PR adds the changelog for MultiQC ${{ steps.convert.outputs.version }} to the Seqera documentation.

            This is an automated PR created from the MultiQC repository.
          branch: changelog-multiqc-${{ steps.convert.outputs.version }}
          base: master
          delete-branch: true
