name: "Windows tests"
on:
  push:
    branches:
      - main
    paths:
      # runs e.g. when version updated, module added, or dependency added
      - "pyproject.toml"
  pull_request:
    paths:
      - "pyproject.toml"

permissions:
  contents: read

jobs:
  windows_tests:
    name: "Windows smoke test"
    runs-on: windows-latest
    timeout-minutes: 15
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: "Set up Python"
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.12"

      - name: "Install MultiQC"
        run: pip install .

      # NB: download the zip instead of git clone, as Windows complains about
      # reserved filenames and certain characters in the test data.
      - name: "Download test data"
        run: |
          Invoke-WebRequest -Uri "https://github.com/MultiQC/test-data/archive/main.zip" -OutFile test-data.zip
          7z x test-data.zip -y -o"test-data"

      # Flat plot export doesn't work on Windows, so force interactive plots.
      # Only run selected modules: some fail when dumping plot JSON with
      # UnicodeEncodeError: 'charmap' codec can't encode character '≥'.
      - name: "Run MultiQC on selected modules"
        run: multiqc --strict --interactive -m fastqc -m samtools -m kallisto -v test-data\test-data-main\data\modules\
